SID='####################'
AUTH_TOKEN='#####################'
FROM_NUMBER='+15735272664'
TO_NUMBER='+918074020784'
API_KEY='%%%%%%%%%%%%%%%%%%%%%%%%%%'
DEVICE_ID='BOLT964690'
MAILGUN_API_KEY='&&&&&&&&&&&&&&&&&&&&&&&&'
SANDBOX_URL=' '
RECEPIENT_EMAIL=' !!!##'
SENDER_EMAIL='############################'
FRAME_SIZE=10
MUL_FACTOR=6
